FROM python:3.10

WORKDIR /app

RUN pip install poetry && \
    python -m poetry config virtualenvs.create true && \
    python -m poetry config virtualenvs.in-project true && \
    python -m poetry config virtualenvs.options.always-copy true

COPY . .
